services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: dsci644_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project1_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # MongoDB NoSQL
  mongodb:
    image: mongo:latest
    container_name: dsci644_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Spark Dev Environment
  spark-app:
    build: .
    container_name: dsci644_spark
    depends_on:
      - db
      - mongodb
    volumes:
      - .:/app
    environment:
      # Use the exact path to the jar for JDBC
      SPARK_CLASSPATH: /opt/spark/jars/mysql-connector-j.jar

volumes:
  mysql_data:
  mongo_data: